apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-image-pipeline-template
  namespace: tekton-worker
spec:
  params:
    - name: git-url
    - name: image
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: build-image-run-
      spec:
        params:
          - name: git-url
            value: $(tt.params.git-url)
          - name: image
            value: $(tt.params.image)
        workspaces:
          - name: docker-creds
            secret:
              secretName: docker-config
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
        pipelineRef:
          name: build-image-pipeline