using ManagementConsole.Application.RequestHandler;

namespace ManagementConsole.Application.UseCase.MemoryDatabase.ExecutionResult;

public class LoadMemoryDatabaseExecuteResult : IUseCaseExecuteResult;