version: '3'
services:
  app:
    init: true
    build:
      context: .
      target: runtime
    container_name: app
    environment:
      - ASPNETCORE_URLS=http://+:5000;
      - DOTNET_GENERATE_ASPNET_CERTIFICATE=false
      - DB_SERVER_HOST=${DB_SERVER_HOST}
      - DB_SERVER_PORT=${DB_SERVER_PORT}
      - DB_SERVER_USER=${DB_SERVER_USER}
      - DB_SERVER_PASSWORD=${DB_SERVER_PASSWORD}
      - OTLP_SERVER_NAME=${OTLP_SERVER_NAME}
      - OTLP_ENDPOINT=${OTLP_ENDPOINT}
      - CACHE_SERVER_HOST=${CACHE_SERVER_HOST}
      - CACHE_SERVER_PORT=${CACHE_SERVER_PORT}
    networks:
      - default
      - shared-network
    logging:
      driver: loki
      options:
        loki-url: 'http://host.docker.internal:3100/loki/api/v1/push'
        # Shortening the time because of the waiting time when loki is not running.
        # Configure options see below 
        # https://grafana.com/docs/loki/latest/clients/docker-driver/configuration/#supported-log-opt-options
        loki-timeout: 1s
        loki-retries: 1

  app_web:
    container_name: web
    image: nginx:1.21.4-alpine
    volumes:
      - ./webserver/nginx/app.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - default
      - shared-network

  app_db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile.MySQL
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=
      - MYSQL_RANDOM_ROOT_PASSWORD=

  app_cache:
    container_name: cache
    image: redis:6.2.6
    ports:
      - "6379:6379"

  workspace:
    container_name: workspace
    build:
      context: .
      target: workspace
    tty: true
    networks:
      - default
      - shared-network
    volumes:
      - ./dotnet-metric-test:/source
    working_dir: /source
    environment:
      - DB_SERVER_HOST=${DB_SERVER_HOST}
      - DB_SERVER_PORT=${DB_SERVER_PORT}
      - DB_SERVER_USER=${DB_SERVER_USER}
      - DB_SERVER_PASSWORD=${DB_SERVER_PASSWORD}
      - OTLP_SERVER_NAME=${OTLP_SERVER_NAME}
      - OTLP_ENDPOINT=${OTLP_ENDPOINT}
      - CACHE_SERVER_HOST=${CACHE_SERVER_HOST}
      - CACHE_SERVER_PORT=${CACHE_SERVER_PORT}

networks:
  shared-network:
    external: true
