FROM mysql:latest
HEALTHCHECK --interval=1s CMD test mysqladmin ping -h localhost -u root -proot

COPY ./database/mysql/test_db-1.0.7.tar.gz /test_db.tar.gz
RUN tar -xvzf /test_db.tar.gz
RUN cp -f ./test_db/*.dump /
RUN cp -f ./test_db/show_elapsed.sql /
RUN cp -f ./test_db/employees.sql /docker-entrypoint-initdb.d/
COPY ./database/mysql/my.cnf /etc/mysql/conf.d/my.cnf

