apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: management-console
    app.kubernetes.io/managed-by: pulumi
  name: management-console
  namespace: tool
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: management-console
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-dotnet: "True"
        sidecar.opentelemetry.io/inject: "True"
      labels:
        app: management-console
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: management-console-env-secret
        image: k3d-wabl-cs-registry:58063/tool/management-console:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: management-console
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: 200m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
