// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Opentelemetry.V1Alpha1
{

    /// <summary>
    /// NodeJS defines configuration for nodejs auto-instrumentation.
    /// </summary>
    [OutputType]
    public sealed class InstrumentationSpecNodejs
    {
        /// <summary>
        /// Env defines nodejs specific env vars. There are four layers for env vars' definitions and the precedence order is: `original container env vars` &gt; `language specific env vars` &gt; `common env vars` &gt; `instrument spec configs' vars`. If the former var had been defined, then the other vars would be ignored.
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Opentelemetry.V1Alpha1.InstrumentationSpecNodejsEnv> Env;
        /// <summary>
        /// Image is a container image with NodeJS SDK and auto-instrumentation.
        /// </summary>
        public readonly string Image;

        [OutputConstructor]
        private InstrumentationSpecNodejs(
            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Opentelemetry.V1Alpha1.InstrumentationSpecNodejsEnv> env,

            string image)
        {
            Env = env;
            Image = image;
        }
    }
}
