apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  namespace: tekton-pipelines
  name: push-dokcer-image
spec:
  inputs:
    resources:
      - name: app
        type: git
    params:
      - name: dockerfile
        default: /workspace/app/Dockerfile
      - name: context
        default: /workspace/app
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor
      command:
        - /kaniko/executor
      args:
        - --dockerfile=${inputs.params.dockerfile}
        - --destination=${outputs.resources.builtImage.url}
        - --context=${inputs.params.context}