apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  namespace: tekton-pipelines
  name: unit-test
spec:
  params:
    - name: project-directory
      default: tests/WebApplication.Test
    - name: build-configration
      default: Release
  workspaces:
    - name: source
      description: The git repo will be cloned onto the volume backing this Workspace.
  steps:
  - name: unit-test
    image: mcr.microsoft.com/dotnet/sdk:6.0.100-alpine3.14
    env:
      - name: PROJECT_DIRECTORY
        value: $(params.project-directory)
      - name: BUILD_CONFIGRATION
        value: $(params.build-configration)
    script: |
      #!/usr/bin/env sh
      cd ${PROJECT_DIRECTORY}
      dotnet restore
      dotnet build --configuration ${BUILD_CONFIGRATION} --no-restore
      dotnet test --no-restore "--logger:Console;verbosity=normal"