apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  namespace: tekton-pipelines
  name: unit-test
spec:
  params:
    - name: source-directory
      default: src
  workspaces:
    - name: source
      description: The git repo will be cloned onto the volume backing this Workspace.
  steps:
  - name: unit-test
    image: mcr.microsoft.com/dotnet/sdk:6.0.100-alpine3.14
    command:
    - /bin/sh
    args:
    - -c
    - "pwd; ls -al; cd $(params.source-directory); ls -al; dotnet test"