apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab
  namespace: cert-manager
spec:
  subject:
    organizations:
    - MyOrg
    countries:
    - Japan
    organizationalUnits:
    - MyUnit
    localities:
    - Kanagawa
    provinces:
    - Yokohama
  commonName: gitlab-cn
  duration: 8760h
  dnsNames:
    - vcs.test
    - '*.gitlab.vcs.test'
  secretName: gitlab-certificate
  issuerRef:
    name: ca-issuer
    kind: Issuer
    group: cert-manager.io
  privateKey:
    algorithm: RSA
    size: 2048