apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor
  namespace: cert-manager
spec:
  subject:
    organizations:
    - MyOrg
    countries:
    - Japan
    organizationalUnits:
    - MyUnit
    localities:
    - Kanagawa
    provinces:
    - Yokohama
  commonName: harbor-cn
  duration: 8760h
  dnsNames:
    - cr.test
    - '*.harbor.cr.test'
  secretName: harbor-certificate
  issuerRef:
    name: ca-issuer
    kind: Issuer
    group: cert-manager.io
  privateKey:
    algorithm: RSA
    size: 2048