// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Pingcap.V1Alpha1
{

    public class TidbMonitorSpecPrometheusRemotewriteBasicauthArgs : Pulumi.ResourceArgs
    {
        [Input("password")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Pingcap.V1Alpha1.TidbMonitorSpecPrometheusRemotewriteBasicauthPasswordArgs>? Password { get; set; }

        [Input("username")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Pingcap.V1Alpha1.TidbMonitorSpecPrometheusRemotewriteBasicauthUsernameArgs>? Username { get; set; }

        public TidbMonitorSpecPrometheusRemotewriteBasicauthArgs()
        {
        }
    }
}
