// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Pingcap.V1Alpha1
{

    public class TidbMonitorStatusArgs : Pulumi.ResourceArgs
    {
        [Input("deploymentStorageStatus")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Pingcap.V1Alpha1.TidbMonitorStatusDeploymentstoragestatusArgs>? DeploymentStorageStatus { get; set; }

        [Input("statefulSet")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Pingcap.V1Alpha1.TidbMonitorStatusStatefulsetArgs>? StatefulSet { get; set; }

        public TidbMonitorStatusArgs()
        {
        }
    }
}
