apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  namespace: tekton-worker
  name: build-image-pipeline-run
spec:
  pipelineRef:
    name: build-image-pipeline
  params:
    - name: git-url
      value: https://github.com/konnta0/wabl-cs
    - name: image
      value: core.harbor.cr.test/webapp/dotnetapp
  serviceAccountName: tekton-dashboard-service-account
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
