// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Pingcap.V1Alpha1
{

    public class TidbClusterSpecPdAdditionalVolumesProjectedSourcesDownwardApiItemsResourceFieldRefArgs : global::Pulumi.ResourceArgs
    {
        [Input("containerName")]
        public Input<string>? ContainerName { get; set; }

        [Input("divisor")]
        public InputUnion<int, string>? Divisor { get; set; }

        [Input("resource", required: true)]
        public Input<string> Resource { get; set; } = null!;

        public TidbClusterSpecPdAdditionalVolumesProjectedSourcesDownwardApiItemsResourceFieldRefArgs()
        {
        }
        public static new TidbClusterSpecPdAdditionalVolumesProjectedSourcesDownwardApiItemsResourceFieldRefArgs Empty => new TidbClusterSpecPdAdditionalVolumesProjectedSourcesDownwardApiItemsResourceFieldRefArgs();
    }
}
