// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Pingcap.V1Alpha1
{

    public class TidbClusterAutoScalerStatusTidbArgs : global::Pulumi.ResourceArgs
    {
        [Input("lastAutoScalingTimestamp")]
        public Input<string>? LastAutoScalingTimestamp { get; set; }

        public TidbClusterAutoScalerStatusTidbArgs()
        {
        }
        public static new TidbClusterAutoScalerStatusTidbArgs Empty => new TidbClusterAutoScalerStatusTidbArgs();
    }
}
