// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Pingcap.V1Alpha1
{

    public class TidbClusterAutoScalerSpecTikvArgs : global::Pulumi.ResourceArgs
    {
        [Input("external")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Pingcap.V1Alpha1.TidbClusterAutoScalerSpecTikvExternalArgs>? External { get; set; }

        [Input("resources")]
        private InputMap<Pulumi.Kubernetes.Types.Inputs.Pingcap.V1Alpha1.TidbClusterAutoScalerSpecTikvResourcesArgs>? _resources;
        public InputMap<Pulumi.Kubernetes.Types.Inputs.Pingcap.V1Alpha1.TidbClusterAutoScalerSpecTikvResourcesArgs> Resources
        {
            get => _resources ?? (_resources = new InputMap<Pulumi.Kubernetes.Types.Inputs.Pingcap.V1Alpha1.TidbClusterAutoScalerSpecTikvResourcesArgs>());
            set => _resources = value;
        }

        [Input("rules")]
        private InputMap<Pulumi.Kubernetes.Types.Inputs.Pingcap.V1Alpha1.TidbClusterAutoScalerSpecTikvRulesArgs>? _rules;
        public InputMap<Pulumi.Kubernetes.Types.Inputs.Pingcap.V1Alpha1.TidbClusterAutoScalerSpecTikvRulesArgs> Rules
        {
            get => _rules ?? (_rules = new InputMap<Pulumi.Kubernetes.Types.Inputs.Pingcap.V1Alpha1.TidbClusterAutoScalerSpecTikvRulesArgs>());
            set => _rules = value;
        }

        [Input("scaleInIntervalSeconds")]
        public Input<int>? ScaleInIntervalSeconds { get; set; }

        [Input("scaleOutIntervalSeconds")]
        public Input<int>? ScaleOutIntervalSeconds { get; set; }

        public TidbClusterAutoScalerSpecTikvArgs()
        {
        }
        public static new TidbClusterAutoScalerSpecTikvArgs Empty => new TidbClusterAutoScalerSpecTikvArgs();
    }
}
