apiVersion: v1
kind: Secret
metadata:
  name: dotnetapp-secret
  namespace: webapp
type: Opaque
stringData:
  MYSQL_SERVER_HOST: "app_db"
  MYSQL_SERVER_PORT: "3306"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "root"
  OTLP_SERVER_NAME: "dotnet-metric"
  OTLP_ENDPOINT: "http://otel-collector:4317"
  REDIS_HOST: "web-application-dragonfly-32f14bbf-redis-master"
  REDIS_PORT: "6379"
  REDIS_USER: "dragonfly"
  REDIS_PASSWORD: "dragonfly"
  