extensions:
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:
    loglevel: info
  otlphttp:
    endpoint: http://mimir-distributed-distributor.observability.svc.cluster.local:8080/otlp
    headers:
      X-Scope-OrgID: "1"
  prometheusremotewrite:
    endpoint: http://mimir-distributed-distributor.observability.svc.cluster.local:8080/api/v1/push
  otlp/tempo-trace:
    endpoint: tempo-distributed-distributor.observability.svc.cluster.local:4317
    tls:
      insecure: true

processors:
  batch:
  memory_limiter:
    # 75% of maximum memory up to 4G
    limit_mib: 1536
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s

service:
  extensions: [zpages]
  telemetry:
    logs:
      level: "INFO"
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/tempo-trace]
    metrics:
      receivers: [otlp]
      exporters: [otlphttp]
