// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Pingcap.V1Alpha1
{

    [OutputType]
    public sealed class TidbMonitorSpecReloader
    {
        public readonly string BaseImage;
        public readonly string ImagePullPolicy;
        public readonly ImmutableDictionary<string, Union<int, string>> Limits;
        public readonly ImmutableDictionary<string, Union<int, string>> Requests;
        public readonly Pulumi.Kubernetes.Types.Outputs.Pingcap.V1Alpha1.TidbMonitorSpecReloaderService Service;
        public readonly string Version;

        [OutputConstructor]
        private TidbMonitorSpecReloader(
            string baseImage,

            string imagePullPolicy,

            ImmutableDictionary<string, Union<int, string>> limits,

            ImmutableDictionary<string, Union<int, string>> requests,

            Pulumi.Kubernetes.Types.Outputs.Pingcap.V1Alpha1.TidbMonitorSpecReloaderService service,

            string version)
        {
            BaseImage = baseImage;
            ImagePullPolicy = imagePullPolicy;
            Limits = limits;
            Requests = requests;
            Service = service;
            Version = version;
        }
    }
}
