// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Pingcap.V1Alpha1
{

    [OutputType]
    public sealed class TidbClusterStatusTicdcCaptures
    {
        public readonly string Id;
        public readonly bool IsOwner;
        public readonly string PodName;
        public readonly bool Ready;
        public readonly string Version;

        [OutputConstructor]
        private TidbClusterStatusTicdcCaptures(
            string id,

            bool isOwner,

            string podName,

            bool ready,

            string version)
        {
            Id = id;
            IsOwner = isOwner;
            PodName = podName;
            Ready = ready;
            Version = version;
        }
    }
}
