// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Pingcap.V1Alpha1
{

    [OutputType]
    public sealed class TidbClusterSpecTiflashConfig
    {
        public readonly ImmutableDictionary<string, object> Config;
        public readonly ImmutableDictionary<string, object> Proxy;

        [OutputConstructor]
        private TidbClusterSpecTiflashConfig(
            ImmutableDictionary<string, object> config,

            ImmutableDictionary<string, object> proxy)
        {
            Config = config;
            Proxy = proxy;
        }
    }
}
