using ManagementConsole.Application.RequestHandler;

namespace ManagementConsole.Application.UseCase.MemoryDatabase.DataTransferObject;

public interface ILoadMemoryDatabaseUseCaseOutput : IUseCaseOutput;