// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Pingcap.V1Alpha1
{

    [OutputType]
    public sealed class TidbClusterStatusTikvFailurestores
    {
        public readonly string CreatedAt;
        public readonly string PodName;
        public readonly string StoreID;

        [OutputConstructor]
        private TidbClusterStatusTikvFailurestores(
            string createdAt,

            string podName,

            string storeID)
        {
            CreatedAt = createdAt;
            PodName = podName;
            StoreID = storeID;
        }
    }
}
