version: '3'
services:
  controller:
    build:
      context: .
      dockerfile: Dockerfile.LoadTest.Controller
      target: runtime
    container_name: controller
    environment:
      - PORT_WEB=7312
      - PORT_WORKER=7313
    ports:
      - "7312:7312"
    networks:
      - default
      - shared-network
  worker:
    build:
      context: .
      dockerfile: Dockerfile.LoadTest.Worker
      target: runtime
    container_name: worker
    environment:
      - APPLICATION_BASE_ADDRESS=http://app_web
      - CONTROLLER_ADDRESS=http://controller:7313
    networks:
      - default
      - shared-network
  rest-api:
    build:
      context: .
      dockerfile: Dockerfile.LoadTest.RestApi
      target: runtime
    container_name: rest-api
    environment:
      - CONTROLLER_ROOT_ADDRESS=http://controller:7312
      - WORKLOAD_NAME=$LOADTEST_WORKLOAD_NAME
      - CONCURRENCY=$LOADTEST_CONCURRENCY
      - TOTAL_REQUEST=$LOADTEST_TOTAL_REQUEST
    networks:
      - default
      - shared-network

networks:
  shared-network:
    external: true
