# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:6.0.100-alpine3.14 AS workspace

FROM workspace AS builder
WORKDIR /build
COPY ./src/Tool/LoadTest ./src/Tool/LoadTest

RUN echo 'Restore&Build Controller'
RUN dotnet restore ./src/Tool/LoadTest/Controller/Controller.csproj  
RUN dotnet publish ./src/Tool/LoadTest/Controller/Controller.csproj -c Release -o out/Controller --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
RUN ln -sf /usr/share/zoneinfo/posix/Japan /etc/localtime
WORKDIR /app
COPY --from=builder /build/out/Controller .
ENTRYPOINT [ "dotnet", "Controller.dll"]

