name: Database/Update

on:
  workflow_dispatch:

jobs:
  buildAndTest:
    runs-on: arc-runner-set
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet 7.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: Update database
        working-directory: ./src/Tool/Make
        run: |
          dotnet run -- migration update
