name: Database/Update

on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: 'Runner set'
        required: true
        default: 'arc-runner-set'

jobs:
  update-database:
    runs-on:  ${{ github.event.inputs.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # see: https://github.com/actions/actions-runner-controller/issues/3130
      - name: Install curl
        run: sudo apt update -y && sudo apt install curl -y

      - name: Setup dotnet 9.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
          # see: https://github.com/actions/setup-dotnet/issues/327#issuecomment-1277284874
        env:
          DOTNET_INSTALL_DIR: "./.dotnet"

      - name: Update database
        working-directory: ./src/Tool.Make
        run: |
          dotnet run -- migration update
