name: Database/Update

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  buildAndTest:
    environment: ${{ github.event.inputs.environment }}
    runs-on: arc-runner-set
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet 8.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Update database
        working-directory: ./src/Tool/Make
        run: |
          dotnet run -- migration update
