name: ManagementConsole/Deploy

on:
  workflow_dispatch:
    inputs:
      deploy-tag:
        description: 'Tag to deploy'
        required: true
        default: 'latest'
env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  STACK: local

jobs:
  deploy:
    runs-on: arc-runner-set
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # see: https://github.com/actions/actions-runner-controller/issues/3130
      - name: Install curl
        run: sudo apt update -y && sudo apt install curl -y

      - name: Install Pulumi
        uses: pulumi/actions@v5
        with:
          pulumi-version: "latest"

      - name: Setup dotnet 8.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
          # see: https://github.com/actions/setup-dotnet/issues/327#issuecomment-1277284874
        env:
          DOTNET_INSTALL_DIR: "./.dotnet"

      - name: Deploy Management Console
        working-directory: ./src/Tool.Make
        run: |
          dotnet run -- management-console deploy --stack ${{ env.STACK }} --tag ${{ inputs.deploy-tag }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ env.PULUMI_ACCESS_TOKEN }}