name: WebApp/Build

on:
  workflow_dispatch:

env:
  CONTAINER_REGISTRY: 192.168.105.27:32000

jobs:
  build:
    runs-on: arc-runner-set
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Setup buildx
      #   uses: docker/setup-buildx-action@v3

      # see: https://github.com/actions/actions-runner-controller/issues/3130
      - name: Install curl
        run: sudo apt update -y && sudo apt install curl -y

      - name: Setup dotnet 8.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
        # see: https://github.com/actions/setup-dotnet/issues/327#issuecomment-1277284874
        env:
          DOTNET_INSTALL_DIR: "./.dotnet"

      - name: Get short sha
        id: short_sha
        run: |
          sha=$(echo ${{ github.sha }} | cut -c1-7)
          echo "sha=$sha" >> $GITHUB_OUTPUT

      # - name: Kaniko build
      #   uses: aevea/action-kaniko@v0.12.0
      #   with:
      #     image: webapp/web-api
      #     registry: 192.168.105.27:32000
      #     tag: ${{ steps.short_sha.outputs.sha }}
      #     build_file: ./Dockerfile
      #     path: .
      #     tag_with_latest: true
      #     username: ""
      #     password: ""

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-config-inline: |
            [registry."${{ env.CONTAINER_REGISTRY }}"]
              http = true
              insecure = true

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.CONTAINER_REGISTRY }}/webapp/web-api:${{ steps.short_sha.outputs.sha }}

      - name: Build and Push Image
        working-directory: ./src/Tool.Make
        run: |
          dotnet run -- web-app push-image --tags ${{ steps.short_sha.outputs.sha }},latest
