name: WebApp/Build

on:
  workflow_dispatch:
    inputs:
      deploy-tag:
        description: 'Tag to deploy'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: arc-runner-set
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet 8.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Build and Push Image
        working-directory: ./src/Tool/Make
        run: |
          dotnet run -- webapp deploy --tag=${{ inputs.deploy-tag }}
